name: Fetch FFXIV Status

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install   # ← これが無いと puppeteer 入らない

      - run: node fetch.js

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "update status" || echo "No changes"
          git push
